# ---------------------------------------------------------------------
# GET /healthcheck/app/status
#  稼働確認(APP)
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/healthcheck/app/status
Content-Type: application/json
Accept: application/json


# ---------------------------------------------------------------------
# GET /healthcheck/db/status
#  稼働確認(DB)
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/healthcheck/db/status
Content-Type: application/json
Accept: application/json

# ---------------------------------------------------------------------
# GET /items
#  商品情報検索
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/items?name=り&category=FRUIT&category=JUICE&sort=price&order=desc
Content-Type: application/json
Accept: application/json

### 異常ケース
GET http://localhost:8091/api/items?minprice=1000&maxprice=100
Content-Type: application/json
Accept: application/json

### 異常ケース
GET http://localhost:8091/api/items?category=DUMMY
Content-Type: application/json
Accept: application/json

# ---------------------------------------------------------------------
# GET /items
#  商品情報検索
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/items/AA000030
Content-Type: application/json
Accept: application/json

### 異常ケース
GET http://localhost:8091/api/items/りんご
Content-Type: application/json
Accept: application/json

### 異常ケース
GET http://localhost:8091/api/items/a
Content-Type: application/json
Accept: application/json

# ---------------------------------------------------------------------
# GET /stocks
#  在庫情報検索
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/stocks
Content-Type: application/json
Accept: application/json

### 異常ケース
GET http://localhost:8091/api/stocks?id=AA000001&id=DUMMY&id=AA000003&id=AA000004&offset=1&limit=1
Content-Type: application/json
Accept: application/json

# ---------------------------------------------------------------------
# GET /stocks/{id}
#  指定された商品の在庫情報を取得
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/stocks/AA000001
Content-Type: application/json
Accept: application/json

### 異常ケース
GET http://localhost:8091/api/stocks/DUMMY
Content-Type: application/json
Accept: application/json

# ---------------------------------------------------------------------
# PUT /stocks/{id}/buy
#  指定された商品の在庫情報を更新するAPI
# ---------------------------------------------------------------------
### 正常ケース
PUT http://localhost:8091/api/stocks/AA000001/buy
Content-Type: application/json
Accept: application/json

{
  "amount": 1
}

### 異常ケース
PUT http://localhost:8091/api/stocks/AA000001/buy
Content-Type: application/json
Accept: application/json

{
  "amount": 101
}

# ---------------------------------------------------------------------
# PUT /stocks/manage
#  指定された商品の在庫情報を管理するAPI
# ---------------------------------------------------------------------
### 正常ケース
PUT http://localhost:8091/api/stocks/manage
Content-Type: application/json
Accept: application/json

{
  "stocks": [
    {
      "id": "AA000001",
      "amount": "100"
    },
    {
      "id": "AA000002",
      "amount": "100"
    },
    {
      "id": "AA000003",
      "amount": "100"
    }
  ]
}

### 異常ケース
PUT http://localhost:8091/api/stocks/manage
Content-Type: application/json
Accept: application/json

{
  "stocks": [
    {
      "id": "AA000001",
      "amount": "100"
    },
    {
      "id": "DUMMY",
      "amount": "100"
    },
    {
      "id": "AA000003",
      "amount": "100"
    }
  ]
}