# ---------------------------------------------------------------------
# GET /healthcheck/app/status
#  稼働確認(APP)
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/healthcheck/app/status
Content-Type: application/json
Accept: application/json


# ---------------------------------------------------------------------
# GET /healthcheck/db/status
#  稼働確認(DB)
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/healthcheck/db/status
Content-Type: application/json
Accept: application/json

# ---------------------------------------------------------------------
# GET /users/{id}
#  ユーザー情報取得
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/users/rikkyrice
Content-Type: application/json
Accept: application/json

# ---------------------------------------------------------------------
# GET /users
#  ユーザー情報一覧取得
# ---------------------------------------------------------------------
### 正常ケース
GET http://localhost:8091/api/users
Content-Type: application/json
Accept: application/json
