server:
  port: 8091
  servlet:
    context-path: /api
spring:
  datasource: 
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  jmx:
    default-domain: api
logging:
  level: 
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  file:
    name: build/tmp/api.log
    max-size: 1000000
    max-history: 1